[general]
ENCRYPTION_KEY = "LcodOA7LCpJXwotBDcBUisxdxpiZNvVo0cPGSHOD3YY="

[connections.supabase]
dialect = "postgresql"
host = "db.iovqpxcfbqqmeauhzvhp.supabase.co"
port = "5432"
database = "postgres"
username = "postgres"
password = "Petsaude2025"
